<?php

echo filter_var(12, FILTER_SANITIZE_NUMBER_FLOAT);
//12

echo filter_var(12.45, FILTER_SANITIZE_NUMBER_FLOAT);
//1245

echo filter_var(12.45, FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION);
//12.45

echo filter_var("12AA.45", FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION);
//12.45
